# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20e362a55fa45ac9c42186a20decdae4c83c742d3ee4b49822c7875ff71d570898f3fdbed19bd46a1deb2cc7c7874fd10eac39aa2009042334e21493b61d829c

test:
  secret_key_base: fc1ee510b4f42c4ef422811835bb4f9c18542237ad5dcd167840f4a867c02c7a1f4dd783605712e4d77c3a48e43aa463ae09ed7a286164d54235d799ebc3830b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
